language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-django-egasimus' ]; then cd .. && eval "mv $currentfolder generator-django-egasimus" && cd generator-django-egasimus; fi

